name: WebApp container deploy workflow

env:
  AZURE_WEBAPP_NAME: spacegame101-web-6669
  AZURE_ACR_NAME: spacegame101acr6669.azurecr.io

on: [push]

jobs:
  build and deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_ACR_NAME }}/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}
    
    - run: |
        docker build -f ./Tailspin.SpaceGame.Web/Dockerfile -t ${{ env.AZURE_ACR_NAME }}/web:${{ github.sha }} .
        docker push ${{ env.AZURE_ACR_NAME }}/web:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: '${{ env.AZURE_ACR_NAME }}/web:${{ github.sha }}' 
